export type DomainId = "agents" | "tools" | "code" | "prompts" | "context";

export type Domain = {
  id: DomainId;
  name: string;
  shortName: string;
  weight: number;
  color: string;
  description: string;
};

export type StudyCard = {
  id: string;
  domain: DomainId;
  eyebrow: string;
  title: string;
  summary: string;
  keyPoints: string[];
  examTip: string;
};

export type Question = {
  id: string;
  domain: DomainId;
  scenario: string;
  prompt: string;
  options: string[];
  correctIndex: number;
  explanation: string;
};

export type CoverageArea = {
  domain: DomainId;
  title: string;
  topics: string[];
};

export type ExamScenario = {
  number: number;
  title: string;
  coverage: "Cubierto" | "Área reportada";
  note: string;
};

export const domains: Domain[] = [
  {
    id: "agents",
    name: "Arquitectura de agentes y orquestación",
    shortName: "Agentes",
    weight: 27,
    color: "violet",
    description: "Diseña agentes, subagentes, delegación y controles de ejecución.",
  },
  {
    id: "tools",
    name: "Diseño de herramientas e integración MCP",
    shortName: "Tools & MCP",
    weight: 18,
    color: "blue",
    description: "Conecta capacidades externas con herramientas y recursos claros.",
  },
  {
    id: "code",
    name: "Claude Code y flujos de trabajo",
    shortName: "Claude Code",
    weight: 20,
    color: "orange",
    description: "Configura memoria, skills, reglas y automatización de calidad.",
  },
  {
    id: "prompts",
    name: "Prompts y salida estructurada",
    shortName: "Prompts",
    weight: 20,
    color: "pink",
    description: "Obtén resultados precisos, validados y accionables.",
  },
  {
    id: "context",
    name: "Contexto y confiabilidad",
    shortName: "Confiabilidad",
    weight: 15,
    color: "teal",
    description: "Protege el contexto, diseña recuperaciones y escala con seguridad.",
  },
];

const foundationalStudyCards: StudyCard[] = [
  {
    id: "agent-loop",
    domain: "agents",
    eyebrow: "Patrón base",
    title: "El ciclo agéntico sigue señales, no intuiciones",
    summary: "Un agente llama al modelo, ejecuta las herramientas solicitadas y continúa hasta que el modelo indica que terminó.",
    keyPoints: [
      "`tool_use` pide ejecutar una herramienta y devolver su resultado.",
      "`end_turn` es la señal fiable para dar la tarea por terminada.",
      "No concluyas una tarea analizando frases como “ya está listo”.",
    ],
    examTip: "Si te preguntan por el fin de un flujo de agente, busca stop_reason = end_turn.",
  },
  {
    id: "coordinator",
    domain: "agents",
    eyebrow: "Multiagente",
    title: "El coordinador es el punto de control",
    summary: "En una topología hub-and-spoke, el coordinador descompone, delega, agrega resultados y controla errores.",
    keyPoints: [
      "Elige subagentes dinámicamente; no lances siempre el mismo pipeline.",
      "Los subagentes tienen contexto aislado.",
      "Pasa al subagente el contexto, la tarea y el formato de salida explícitamente.",
    ],
    examTip: "Delegar “analiza el documento” sin adjuntar el documento es un antipatrón.",
  },
  {
    id: "hooks",
    domain: "agents",
    eyebrow: "Control determinista",
    title: "Usa hooks para reglas que no pueden fallar",
    summary: "Las instrucciones en prompts orientan; los hooks interceptan de forma determinista momentos del ciclo de vida.",
    keyPoints: [
      "PreToolUse puede bloquear o redirigir una operación antes de ejecutarla.",
      "PostToolUse puede normalizar y reducir el resultado de una herramienta.",
      "Las reglas financieras, legales o de seguridad no deben depender solo de un prompt.",
    ],
    examTip: "Una regla crítica de reembolso se aplica con un hook, no con “por favor, no…”.",
  },
  {
    id: "tool-description",
    domain: "tools",
    eyebrow: "Tool design",
    title: "La descripción de una herramienta es su interfaz de decisión",
    summary: "El modelo elige herramientas según sus descripciones, por lo que deben diferenciar propósito, entradas, salidas y límites.",
    keyPoints: [
      "Explica qué hace, qué devuelve y cuándo usarla frente a alternativas.",
      "Incluye formatos y ejemplos para los parámetros de entrada.",
      "Evita nombres y descripciones solapados para herramientas similares.",
    ],
    examTip: "Si el agente elige mal entre dos tools, mejora las descripciones antes de añadir lógica rígida.",
  },
  {
    id: "tool-choice",
    domain: "tools",
    eyebrow: "Control de tools",
    title: "Elige la fuerza adecuada con tool_choice",
    summary: "`auto` deja decidir al modelo; `any` exige alguna herramienta; una tool por nombre fuerza una operación concreta.",
    keyPoints: [
      "Usa `auto` para conversaciones y tareas abiertas.",
      "Usa `any` cuando necesitas salida estructurada obligatoria.",
      "Fuerza una tool específica cuando el orden importa.",
    ],
    examTip: "“Garantiza una llamada de extracción” normalmente apunta a tool_choice: any.",
  },
  {
    id: "mcp-primitives",
    domain: "tools",
    eyebrow: "MCP",
    title: "Distingue acciones, contexto y plantillas",
    summary: "MCP separa herramientas para actuar, recursos para aportar contexto y prompts como plantillas reutilizables.",
    keyPoints: [
      "Tools: ejecutar acciones o consultar servicios.",
      "Resources: exponer documentación, catálogos o esquemas como contexto.",
      "Prompts: estandarizar tareas recurrentes.",
    ],
    examTip: "Para que el agente descubra un catálogo sin ejecutar una acción, ofrece un resource.",
  },
  {
    id: "mcp-errors",
    domain: "tools",
    eyebrow: "Recuperación",
    title: "Un error útil enseña al agente qué hacer después",
    summary: "Las fallas de herramientas deben ser estructuradas, con isError, categoría, posibilidad de reintento y contexto seguro.",
    keyPoints: [
      "Indica si el error es transitorio y si se puede reintentar.",
      "Incluye la consulta intentada y resultados parciales cuando ayuden.",
      "Evita mensajes opacos como “Operation failed”.",
    ],
    examTip: "El objetivo no es solo registrar el error: es permitir una siguiente decisión correcta.",
  },
  {
    id: "memory-hierarchy",
    domain: "code",
    eyebrow: "Memoria de proyecto",
    title: "Coloca cada instrucción en el nivel correcto",
    summary: "Las preferencias personales viven con el usuario; las reglas compartidas viven en el repositorio; las reglas locales viven cerca de su código.",
    keyPoints: [
      "CLAUDE.md de usuario: preferencias individuales y no versionadas.",
      "CLAUDE.md del proyecto: convenciones que recibe todo el equipo.",
      "Reglas de directorio: detalles que aplican a una zona concreta.",
    ],
    examTip: "Una regla que debe recibir un colega al clonar no puede vivir en el directorio personal.",
  },
  {
    id: "skills-rules",
    domain: "code",
    eyebrow: "Flujos repetibles",
    title: "Skills para tareas bajo demanda; reglas para convenciones",
    summary: "Una skill encapsula un flujo invocable, mientras que CLAUDE.md y las reglas definen el comportamiento que debe aplicarse siempre.",
    keyPoints: [
      "Una skill puede limitar herramientas y ejecutarse en contexto aislado.",
      "Las reglas con paths cargan solo donde son relevantes.",
      "No conviertas cada estándar universal en una skill manual.",
    ],
    examTip: "Revisión de código invocable: skill. Convención de pruebas de todo el proyecto: regla.",
  },
  {
    id: "plan-mode",
    domain: "code",
    eyebrow: "Decisión de flujo",
    title: "Planifica primero cuando el cambio es incierto o amplio",
    summary: "El modo de planificación sirve para explorar y diseñar sin editar, especialmente antes de decisiones de arquitectura o migraciones grandes.",
    keyPoints: [
      "Úsalo para bases desconocidas y cambios con varios enfoques válidos.",
      "Pasa a ejecución una vez revisado el plan.",
      "Una corrección puntual y clara puede ir directo a ejecución.",
    ],
    examTip: "Gran refactor + requisitos ambiguos = primero exploración y plan.",
  },
  {
    id: "schemas",
    domain: "prompts",
    eyebrow: "Salida estructurada",
    title: "El esquema garantiza forma, no verdad",
    summary: "Forzar una herramienta con esquema JSON elimina errores sintácticos, pero no evita por sí solo datos semánticamente incorrectos.",
    keyPoints: [
      "Los campos required deben ser realmente disponibles en la fuente.",
      "Usa campos nullable cuando una pieza de información puede faltar.",
      "Valida reglas de negocio y aplica reintentos para la exactitud semántica.",
    ],
    examTip: "JSON válido no equivale a una factura bien calculada.",
  },
  {
    id: "prompt-precision",
    domain: "prompts",
    eyebrow: "Diseño de prompt",
    title: "Haz explícitos los límites y los casos inciertos",
    summary: "Un prompt sólido define la tarea, el contexto, el formato y qué hacer cuando falta evidencia o hay ambigüedad.",
    keyPoints: [
      "Incluye ejemplos cuando el formato o clasificación es ambiguo.",
      "Permite valores `unclear` u `other` para evitar invenciones.",
      "Separa preferencia de control: un prompt no sustituye una protección técnica.",
    ],
    examTip: "Un campo “desconocido” es mejor que forzar una clasificación inventada.",
  },
  {
    id: "context-window",
    domain: "context",
    eyebrow: "Context engineering",
    title: "Trata el contexto como un presupuesto limitado",
    summary: "El contexto incluye instrucciones, historial, tools y sus resultados; hay que cuidar qué entra y en qué orden.",
    keyPoints: [
      "La información crítica funciona mejor al inicio o al final de entradas largas.",
      "Reduce respuestas voluminosas de herramientas a los campos necesarios.",
      "Al resumir, conserva identificadores, importes, fechas y decisiones verificables.",
    ],
    examTip: "No envíes cuarenta campos si la tarea solo necesita cinco.",
  },
  {
    id: "reliability",
    domain: "context",
    eyebrow: "Producción",
    title: "Diseña recuperaciones y escalamiento desde el inicio",
    summary: "La confiabilidad combina errores clasificables, reintentos seguros, validación y rutas humanas para situaciones de riesgo.",
    keyPoints: [
      "Diferencia errores transitorios de errores que requieren revisión.",
      "No reintentes indefinidamente operaciones con efecto externo.",
      "Escala a una persona cuando el riesgo, la ambigüedad o una política lo exigen.",
    ],
    examTip: "La automatización madura sabe cuándo detenerse y pedir ayuda.",
  },
];

const expandedStudyCards: StudyCard[] = [
  {
    id: "agent-failure-signals",
    domain: "agents",
    eyebrow: "Ciclo de vida",
    title: "Trata max_tokens como una respuesta incompleta",
    summary: "Además de tool_use y end_turn, el ciclo debe reconocer max_tokens y stop_sequence para no presentar una salida truncada como una respuesta final.",
    keyPoints: ["max_tokens indica que la generación se cortó; aumenta el límite o divide la tarea.", "Una stop sequence requiere procesar la condición definida por tu aplicación.", "Un límite de iteraciones puede proteger recursos, pero no sustituye la señal de finalización."],
    examTip: "Si falta la conclusión porque se agotó la salida, el problema es max_tokens, no end_turn.",
  },
  {
    id: "agent-definition-boundaries",
    domain: "agents",
    eyebrow: "AgentDefinition",
    title: "El rol del agente se define también por lo que no puede hacer",
    summary: "Nombre, descripción, prompt y allowed_tools delimitan la responsabilidad y reducen decisiones incorrectas.",
    keyPoints: ["Otorga solo las tools que el rol necesita: privilegio mínimo.", "El coordinador necesita Task para delegar; un subagente no necesita todas las tools del coordinador.", "Describe objetivos y criterios de calidad, no una cadena rígida de pasos."],
    examTip: "Un agente especializado con 4–5 tools relevantes suele ser más fiable que uno con un catálogo enorme.",
  },
  {
    id: "workflow-preconditions",
    domain: "agents",
    eyebrow: "Guardrails",
    title: "Las precondiciones protegen el orden de operaciones",
    summary: "Las operaciones sensibles necesitan verificaciones programáticas antes de habilitarse, incluso si el prompt explica el orden correcto.",
    keyPoints: ["Bloquea process_refund hasta validar la identidad y el pedido.", "Divide solicitudes compuestas en elementos verificables antes de actuar.", "Usa código para garantizar dependencias; usa prompts para orientar decisiones flexibles."],
    examTip: "Identidad antes de reembolso es una precondición programática, no un deseo en el system prompt.",
  },
  {
    id: "task-decomposition",
    domain: "agents",
    eyebrow: "Descomposición",
    title: "Escoge pipeline fijo o plan adaptativo según la incertidumbre",
    summary: "Las tareas previsibles se benefician de pasos secuenciales; las investigaciones abiertas requieren generar subtareas a partir de hallazgos intermedios.",
    keyPoints: ["Prompt chaining sirve para etapas estables y ordenadas.", "La descomposición adaptativa evita planear detalles que todavía no conoces.", "En revisión de código amplia: análisis por archivo y luego una pasada de integración."],
    examTip: "No conviertas una investigación abierta en un pipeline fijo solo por parecer más simple.",
  },
  {
    id: "sessions-forking",
    domain: "agents",
    eyebrow: "Sesiones",
    title: "Reanuda contexto vigente; bifurca para comparar enfoques",
    summary: "Las sesiones nombradas permiten continuar trabajo, mientras que fork_session crea rutas independientes desde una base común.",
    keyPoints: ["Usa --resume cuando el contexto y los archivos siguen vigentes.", "Usa fork_session para investigar soluciones alternativas sin mezclar resultados.", "Si el estado cambió mucho, inicia una sesión nueva con un resumen estructurado y actualizado."],
    examTip: "Reanudar una investigación con archivos ya modificados puede ser peor que empezar con un resumen actual.",
  },
  {
    id: "tool-scope",
    domain: "tools",
    eyebrow: "Privilegio mínimo",
    title: "Una herramienta específica previene usos fuera de rol",
    summary: "Las interfaces limitadas convierten comportamientos no deseados en imposibles en lugar de solo pedir al modelo que los evite.",
    keyPoints: ["Reemplaza fetch_url genérica por load_document si el rol solo procesa documentos.", "Reduce el conjunto de tools de cada agente a su especialización.", "No mezcles tools de búsqueda, modificación y acciones sensibles sin necesidad."],
    examTip: "Restringir la interfaz es más robusto que una instrucción que dice “no uses esa herramienta para X”.",
  },
  {
    id: "mcp-configuration",
    domain: "tools",
    eyebrow: "Configuración MCP",
    title: "Diferencia la integración de equipo de los experimentos personales",
    summary: "Los servidores compartidos se versionan en .mcp.json; las configuraciones personales viven en ~/.claude.json.",
    keyPoints: ["Usa variables como ${GITHUB_TOKEN}; nunca versionas un token literal.", "Al conectar un servidor, sus tools y resources se descubren junto con los de otros servidores.", "Para integraciones estándar, evalúa primero servidores comunitarios mantenidos."],
    examTip: "Una integración que todos deben recibir con el proyecto pertenece a .mcp.json.",
  },
  {
    id: "builtin-tools",
    domain: "tools",
    eyebrow: "Claude Code",
    title: "Explora una base de código de forma incremental",
    summary: "La selección correcta de herramientas integradas reduce contexto y evita cambios riesgosos.",
    keyPoints: ["Glob encuentra archivos por patrón; Grep encuentra contenido dentro de archivos.", "Lee puntos de entrada después de buscar símbolos y sigue sus llamadas gradualmente.", "Edit es para cambios puntuales con coincidencia única; si falla, Read + Write es el fallback."],
    examTip: "Buscar funciones por contenido es Grep; buscar todos los archivos *.test.ts es Glob.",
  },
  {
    id: "context-commands",
    domain: "code",
    eyebrow: "Higiene de contexto",
    title: "Compacta y revisa memoria de forma intencional",
    summary: "Los comandos de contexto ayudan a sostener sesiones largas, pero la información crítica debe preservarse de forma estructurada.",
    keyPoints: ["/compact reduce historial cuando la conversación se vuelve extensa.", "/memory muestra o ayuda a gestionar instrucciones persistentes disponibles para Claude Code.", "Antes de compactar, separa decisiones, IDs y datos exactos que no se pueden perder."],
    examTip: "Compactar no reemplaza guardar hechos transaccionales en un bloque estructurado.",
  },
  {
    id: "headless-ci",
    domain: "code",
    eyebrow: "Automatización",
    title: "En CI usa ejecución no interactiva y resultados parseables",
    summary: "Claude Code puede ejecutarse en pipelines para tareas delimitadas, con salida JSON validable por el sistema que lo invoca.",
    keyPoints: ["-p / --print permite ejecución no interactiva.", "--output-format json y --json-schema facilitan automatizar la evaluación posterior.", "Separa una instancia que genera de otra que revisa para evitar que valide su propio trabajo sin contraste."],
    examTip: "En CI, el formato estructurado es parte del contrato entre Claude Code y el pipeline.",
  },
  {
    id: "api-message-contract",
    domain: "prompts",
    eyebrow: "Claude API",
    title: "Una solicitud combina instrucciones, historial y capacidades",
    summary: "El comportamiento depende del system prompt, messages, modelo, max_tokens y las definiciones de tools enviadas en cada petición.",
    keyPoints: ["El system prompt tiene alta prioridad y se envía fuera del array messages.", "El historial relevante debe reenviarse: la API no conserva estado implícito entre llamadas.", "Los resultados de tools regresan como bloques tool_result para que el modelo decida el siguiente paso."],
    examTip: "Un patrón de tool inesperado puede originarse en una asociación creada por el system prompt.",
  },
  {
    id: "few-shot",
    domain: "prompts",
    eyebrow: "Few-shot",
    title: "Los ejemplos enseñan la frontera entre casos parecidos",
    summary: "Dos a cuatro ejemplos relevantes son especialmente útiles cuando hay ambigüedad, formatos variables o elecciones entre alternativas plausibles.",
    keyPoints: ["Muestra casos límite, no solo casos obvios.", "Explica la elección cuando varias tools o categorías parecen posibles.", "Mantén los ejemplos representativos del formato de producción."],
    examTip: "Para mejorar selección en casos ambiguos, usa pocos ejemplos comparativos y con justificación.",
  },
  {
    id: "prompt-chaining-interview",
    domain: "prompts",
    eyebrow: "Patrones",
    title: "Encadena fases; entrevista solo cuando la aclaración cambia la solución",
    summary: "Separar análisis, extracción, validación y síntesis reduce atención diluida. Las preguntas aclaratorias deben ser útiles, no una barrera de entrada.",
    keyPoints: ["Un chaining define entradas y salidas claras para cada etapa.", "Para una solicitud vaga, puede ser mejor avanzar con supuestos declarados que abrir muchas preguntas.", "Agrupa las preguntas necesarias en un solo turno cuando sí requieres información del usuario."],
    examTip: "No pidas cuatro aclaraciones si puedes entregar un primer resultado útil con supuestos visibles.",
  },
  {
    id: "validation-feedback",
    domain: "prompts",
    eyebrow: "Calidad",
    title: "Valida, devuelve el error y permite corregir",
    summary: "La salida estructurada protege la forma; las reglas semánticas requieren validación, feedback y, cuando aplica, autocorrección.",
    keyPoints: ["Valida tipos, campos y reglas de negocio por separado.", "En retry-with-feedback, devuelve la discrepancia concreta, no un “inténtalo de nuevo”.", "La autocorrección compara el valor declarado con el calculado y trata el conflicto explícitamente."],
    examTip: "Pydantic puede validar datos y exponer un esquema; no sustituye la verificación semántica.",
  },
  {
    id: "message-batches",
    domain: "prompts",
    eyebrow: "Procesamiento por lotes",
    title: "Batch API sirve para volumen diferible, no para conversaciones",
    summary: "Message Batches procesa solicitudes independientes de forma asíncrona; es útil si puedes esperar y no necesitas un diálogo multi-turn inmediato.",
    keyPoints: ["Asigna custom_id para reconciliar cada respuesta con su entrada.", "Maneja fallos por elemento: un lote puede tener resultados mixtos.", "No uses Batch API si cada respuesta necesita el resultado de la anterior en tiempo real."],
    examTip: "Procesar miles de documentos independientes con SLA flexible apunta a Batch API.",
  },
  {
    id: "case-facts",
    domain: "context",
    eyebrow: "Estado crítico",
    title: "Extrae hechos del caso fuera del resumen conversacional",
    summary: "Montos, fechas, IDs, preferencias y decisiones deben mantenerse en un bloque estructurado que viaje con cada solicitud importante.",
    keyPoints: ["Actualiza el bloque cuando aparece un hecho verificable nuevo.", "No dependas de una sumarización narrativa para conservar porcentajes o números de pedido.", "Distingue hechos confirmados, pendientes y contradictorios."],
    examTip: "Si un descuento exacto se pierde tras compactar, falta un bloque persistente de hechos.",
  },
  {
    id: "scratchpad-recovery",
    domain: "context",
    eyebrow: "Trabajo largo",
    title: "Usa scratchpads y estado recuperable para no repetir razonamiento",
    summary: "Un archivo de trabajo estructurado puede conservar hallazgos, cobertura y próximos pasos, incluso si una sesión se interrumpe.",
    keyPoints: ["Registra decisiones, fuentes, elementos procesados y pendientes.", "Delegar una subtarea a un subagente también protege el contexto principal.", "Para recuperación de crash, preserva estado de forma estructurada, no solo prosa resumida."],
    examTip: "Un scratchpad es útil para trabajo intermedio; la respuesta final debe seguir teniendo evidencia y cobertura claras.",
  },
  {
    id: "handoff-confidence",
    domain: "context",
    eyebrow: "Human-in-the-loop",
    title: "Escala con una razón y un handoff autosuficiente",
    summary: "La persona que recibe el caso debe entender qué ocurrió, qué se intentó, qué evidencia existe y cuál es la acción recomendada.",
    keyPoints: ["Usa desencadenantes confiables: solicitud explícita, política no cubierta, alto riesgo o ambigüedad material.", "Incluye ID, resumen, fuentes/datos, pasos realizados y siguiente acción sugerida.", "Los scores de confianza son más útiles por campo o decisión que como una cifra global opaca."],
    examTip: "Un sentimiento negativo por sí solo no es un disparador fiable de escalamiento.",
  },
  {
    id: "partial-coverage",
    domain: "context",
    eyebrow: "Degradación segura",
    title: "No ocultes huecos: anota la cobertura parcial",
    summary: "Cuando algunos subagentes o fuentes fallan, conserva los resultados válidos y declara con precisión qué conclusiones tienen evidencia incompleta.",
    keyPoints: ["Maneja localmente los fallos transitorios que el subagente puede resolver.", "Propaga al coordinador errores no resolubles con la consulta, pasos intentados y resultados parciales.", "La síntesis final debe marcar áreas cubiertas, parciales y faltantes."],
    examTip: "Una salida útil con cobertura parcial explícita es preferible a un éxito silenciosamente incompleto.",
  },
  {
    id: "provenance",
    domain: "context",
    eyebrow: "Provenance",
    title: "Conserva cada afirmación junto a su fuente y fecha",
    summary: "La atribución permite auditar conclusiones, resolver conflictos y presentar información sensible al tiempo de manera responsable.",
    keyPoints: ["Mantén la relación afirmación → fuente/URL → fecha.", "Ante conflicto, conserva ambos valores y su atribución antes de reconciliarlos.", "Renderiza y comunica el contenido según su tipo, evidencia y vigencia."],
    examTip: "No elijas silenciosamente una cifra entre dos fuentes creíbles y contradictorias.",
  },
];

export const studyCards = [...foundationalStudyCards, ...expandedStudyCards];

export const examCoverage: CoverageArea[] = [
  { domain: "agents", title: "Arquitectura de agentes y orquestación", topics: ["Ciclo agéntico, stop_reason y manejo de max_tokens", "AgentDefinition, allowed_tools, Task y transferencia explícita de contexto", "Hub-and-spoke, paralelismo, agregación y comunicación controlada", "Precondiciones, hooks, normalización y guardrails deterministas", "Pipelines fijos vs descomposición adaptativa", "Sesiones, --resume y fork_session"] },
  { domain: "tools", title: "Herramientas e integración MCP", topics: ["Descripciones, contratos y esquemas de tools", "tool_choice y distribución de capacidades por rol", "Errores MCP estructurados, recuperación y resultados parciales", "Tools, resources, prompts y servidores MCP", ".mcp.json, configuración personal, secretos y servidores comunitarios", "Read, Write, Edit, Bash, Grep y Glob"] },
  { domain: "code", title: "Configuración y flujos de Claude Code", topics: ["Jerarquía de CLAUDE.md, alcance y @path", ".claude/rules con paths y carga condicional", "Comandos slash y skills con context: fork, allowed-tools y argument-hint", "Plan Mode, ejecución directa, /compact y /memory", "Sesiones, headless CLI, JSON Schema y CI/CD"] },
  { domain: "prompts", title: "Prompts y salida estructurada", topics: ["Solicitud API, roles, system prompt y contexto", "Criterios explícitos, severidad y reducción de falsos positivos", "Few-shot para ambigüedad y selección de tools", "JSON Schema: required, nullable, enum y exactitud semántica", "Prompt chaining, entrevista, validación, retry-with-feedback y self-correction", "Message Batches, custom_id, fallos parciales y casos de uso"] },
  { domain: "context", title: "Contexto y confiabilidad", topics: ["Ventana de contexto, lost-in-the-middle y recorte de resultados", "Bloques de hechos, entrada consciente de posición y scratchpads", "Delegación para proteger contexto y estado recuperable", "Human-in-the-loop, handoffs y calibración de confianza", "Errores multiagente, degradación controlada y anotaciones de cobertura", "Provenance, conflictos, fechas y presentación de evidencia"] },
];

export const examScenarios: ExamScenario[] = [
  { number: 1, title: "Agente de soporte al cliente", coverage: "Cubierto", note: "Identidad, pedidos, reembolsos, escalamiento y guardrails." },
  { number: 2, title: "Generación de código con Claude Code", coverage: "Cubierto", note: "Memoria, rules, skills, plan mode y exploración de código." },
  { number: 3, title: "Sistema de investigación multiagente", coverage: "Cubierto", note: "Delegación, síntesis, errores, cobertura y provenance." },
  { number: 4, title: "Herramientas de productividad para desarrolladores", coverage: "Cubierto", note: "Tools integradas, exploración incremental y privilegio mínimo." },
  { number: 5, title: "Claude Code para integración continua", coverage: "Cubierto", note: "CLI headless, salida estructurada y criterios de revisión." },
  { number: 6, title: "Extracción de datos estructurados", coverage: "Cubierto", note: "Esquemas, validación semántica, retry y batches." },
  { number: 7, title: "Patrones de arquitectura de IA conversacional", coverage: "Cubierto", note: "Historial, hechos persistentes, ambigüedad y escalamiento." },
  { number: 8, title: "Herramientas de IA agéntica", coverage: "Área reportada", note: "La guía fuente declara que no hay contenido público verificable; se cubren principios generales, sin afirmar cobertura oficial." },
];

export const flashcards = studyCards.map((card) => ({
  id: card.id,
  domain: card.domain,
  front: card.title,
  back: card.keyPoints.join(" "),
}));

const coreQuestions: Question[] = [
  {
    id: "q-agent-finish",
    domain: "agents",
    scenario: "Agente de soporte",
    prompt: "¿Qué condición debe usar el orquestador para saber que el agente terminó una tarea?",
    options: ["Que la respuesta contenga la frase 'tarea completada'", "Que stop_reason sea `end_turn`", "Que haya hecho cinco iteraciones", "Que no haya texto en la respuesta"],
    correctIndex: 1,
    explanation: "`end_turn` es la señal explícita de finalización. El texto y un límite arbitrario de vueltas no son señales fiables.",
  },
  {
    id: "q-subagent-context",
    domain: "agents",
    scenario: "Investigación multiagente",
    prompt: "Un subagente debe analizar un contrato mencionado en la conversación principal. ¿Qué debe hacer el coordinador?",
    options: ["Asumir que el subagente hereda todo el historial", "Pasarle el contrato, el objetivo y el formato de salida", "Guardar el contrato únicamente en la memoria del usuario", "Pedir al subagente que primero adivine el contexto"],
    correctIndex: 1,
    explanation: "Los subagentes tienen contexto aislado; el coordinador debe transferir explícitamente la información que necesitan.",
  },
  {
    id: "q-critical-control",
    domain: "agents",
    scenario: "Reembolsos",
    prompt: "Se debe impedir de forma garantizada que un agente emita reembolsos mayores de $500. ¿Cuál es la mejor medida?",
    options: ["Añadir 'nunca reembolsa más de $500' al prompt", "Usar un hook PreToolUse que bloquee o escale la llamada", "Bajar la temperatura a 0", "Limitar el número de herramientas a una"],
    correctIndex: 1,
    explanation: "Un hook aplica una regla determinista antes de una operación externa. Las instrucciones en un prompt son probabilísticas.",
  },
  {
    id: "q-parallel-work",
    domain: "agents",
    scenario: "Investigación multiagente",
    prompt: "¿Cuándo conviene que el coordinador lance varios subagentes en paralelo?",
    options: ["Siempre, para demostrar que es multiagente", "Solo si las subtareas son independientes y sus resultados pueden agregarse", "Nunca, porque los subagentes no pueden devolver resultados", "Solo si todos consultan la misma fuente"],
    correctIndex: 1,
    explanation: "La paralelización reduce latencia cuando las subtareas son independientes; el coordinador sigue siendo responsable de agregarlas y validarlas.",
  },
  {
    id: "q-description",
    domain: "tools",
    scenario: "Diseño de herramientas",
    prompt: "Dos tools similares se confunden con frecuencia. ¿Qué mejora ataca primero la causa?",
    options: ["Darles descripciones precisas y claramente diferenciadas", "Ponerles el mismo nombre", "Eliminar las validaciones de parámetros", "Forzar siempre la primera tool"],
    correctIndex: 0,
    explanation: "La descripción es el principal mecanismo de selección de tools. Debe señalar entradas, salidas, límites y diferencias respecto de alternativas.",
  },
  {
    id: "q-tool-any",
    domain: "tools",
    scenario: "Extracción estructurada",
    prompt: "Necesitas que el modelo llame alguna herramienta de extracción, pero puede elegir entre varias. ¿Qué configuración corresponde?",
    options: ["tool_choice: auto", "tool_choice: any", "No incluir tools", "Una secuencia de parada"],
    correctIndex: 1,
    explanation: "`any` exige una llamada a alguna de las herramientas disponibles. `auto` permite responder sin llamar ninguna.",
  },
  {
    id: "q-mcp-resource",
    domain: "tools",
    scenario: "Integración MCP",
    prompt: "Quieres que un agente consulte el esquema de una base de datos como contexto, sin ejecutar una acción. ¿Qué primitiva MCP es adecuada?",
    options: ["Tool", "Resource", "Hook", "Stop sequence"],
    correctIndex: 1,
    explanation: "Los resources proporcionan contexto —por ejemplo, esquemas y documentación— sin representar una acción operacional.",
  },
  {
    id: "q-mcp-error",
    domain: "tools",
    scenario: "Herramienta de pedidos",
    prompt: "Una API de pedidos expira temporalmente. ¿Qué respuesta permite al agente recuperarse mejor?",
    options: ["'Operation failed'", "Un error con isError, categoría transitoria y señal de reintento", "Una respuesta vacía", "Un resultado correcto inventado"],
    correctIndex: 1,
    explanation: "Un error estructurado revela si se puede reintentar y conserva el contexto que ayuda a elegir el siguiente paso.",
  },
  {
    id: "q-project-memory",
    domain: "code",
    scenario: "Nuevo integrante",
    prompt: "Las convenciones de pruebas deben estar disponibles para toda persona que clone el repositorio. ¿Dónde van?",
    options: ["En el CLAUDE.md personal del autor", "En una instrucción de proyecto versionada", "Solo en el historial de chat", "En un comentario no versionado del IDE"],
    correctIndex: 1,
    explanation: "Las instrucciones compartidas deben vivir en el proyecto y en control de versiones, no en la configuración privada de una persona.",
  },
  {
    id: "q-skill-rule",
    domain: "code",
    scenario: "Flujo del equipo",
    prompt: "El equipo quiere invocar bajo demanda un análisis arquitectónico con herramientas de solo lectura. ¿Qué encaja mejor?",
    options: ["Una skill con allowed-tools restringidas", "Un prompt de usuario sin límites", "Una variable de entorno secreta", "Un resumen del último commit"],
    correctIndex: 0,
    explanation: "Una skill hace el flujo reutilizable y puede limitar explícitamente las herramientas disponibles.",
  },
  {
    id: "q-plan-mode",
    domain: "code",
    scenario: "Migración",
    prompt: "Debes migrar una biblioteca usada en decenas de archivos y existen varios enfoques válidos. ¿Cuál es el primer paso?",
    options: ["Aplicar cambios directos sin explorar", "Usar modo de planificación para investigar y proponer el diseño", "Eliminar las pruebas para avanzar más rápido", "Pedir al modelo que edite todos los archivos a la vez"],
    correctIndex: 1,
    explanation: "Los cambios amplios, inciertos o arquitectónicos requieren exploración y diseño antes de ejecutar modificaciones.",
  },
  {
    id: "q-ci-prompt",
    domain: "code",
    scenario: "Revisión CI/CD",
    prompt: "Para reducir falsos positivos en una revisión automática de PR, el prompt debe…",
    options: ["Reportar cualquier diferencia de formato", "Definir criterios, evidencia requerida y qué no debe reportar", "Ignorar el diff del PR", "Pedir siempre comentarios críticos"],
    correctIndex: 1,
    explanation: "Los criterios específicos y la evidencia solicitada acotan el juicio y reducen alertas irrelevantes.",
  },
  {
    id: "q-json-semantic",
    domain: "prompts",
    scenario: "Extracción de facturas",
    prompt: "Una salida cumple el esquema JSON, pero la suma de sus importes es incorrecta. ¿Qué demuestra esto?",
    options: ["El esquema no pudo garantizar una regla semántica", "JSON Schema valida todos los cálculos", "La respuesta debe ser correcta porque es JSON", "El modelo no recibió un prompt de sistema"],
    correctIndex: 0,
    explanation: "El esquema protege sintaxis y estructura, no la verdad de las relaciones entre los valores. Hace falta validación de negocio.",
  },
  {
    id: "q-nullable",
    domain: "prompts",
    scenario: "Extracción documental",
    prompt: "El número de orden puede no aparecer en algunos documentos. ¿Cómo debe modelarse?",
    options: ["Como campo obligatorio de tipo string", "Como campo nullable u opcional según el contrato", "Eliminándolo del resultado", "Rellenándolo con '0000'"],
    correctIndex: 1,
    explanation: "Un campo nullable permite representar ausencia de evidencia sin obligar al modelo a inventar un valor.",
  },
  {
    id: "q-enum-unclear",
    domain: "prompts",
    scenario: "Clasificación",
    prompt: "¿Por qué incluir una categoría `unclear` en un esquema de clasificación?",
    options: ["Para aumentar artificialmente el número de categorías", "Para que el modelo pueda reconocer incertidumbre en vez de inventar", "Para ocultar todos los errores", "Para evitar usar ejemplos"],
    correctIndex: 1,
    explanation: "Reconocer incertidumbre es más seguro que forzar una categoría incorrecta cuando la evidencia no alcanza.",
  },
  {
    id: "q-history",
    domain: "context",
    scenario: "Conversación de soporte",
    prompt: "¿Qué debes enviar en una nueva llamada si quieres que el modelo mantenga coherencia con una conversación anterior?",
    options: ["Solo el último mensaje del usuario", "El historial pertinente de mensajes", "Nada: el modelo recuerda todas las peticiones", "Únicamente las definiciones de tools"],
    correctIndex: 1,
    explanation: "Las llamadas son independientes; el historial necesario debe enviarse de nuevo como parte del contexto.",
  },
  {
    id: "q-tool-results",
    domain: "context",
    scenario: "Agente de soporte",
    prompt: "Una tool devuelve 40 campos pero la decisión solo necesita cinco. ¿Cuál es la mejor práctica?",
    options: ["Pasar siempre los 40 campos al modelo", "Reducir o transformar el resultado a los cinco campos relevantes", "Eliminar por completo la tool", "Repetir la llamada hasta que devuelva menos campos"],
    correctIndex: 1,
    explanation: "Reducir resultados protege el presupuesto de contexto y disminuye distracciones para el modelo.",
  },
  {
    id: "q-lost-middle",
    domain: "context",
    scenario: "Documento extenso",
    prompt: "¿Dónde conviene colocar una instrucción especialmente crítica dentro de una entrada larga?",
    options: ["Solo en el centro", "Al inicio o al final, donde suele retenerse mejor", "Dentro de un campo opcional al azar", "No importa su posición"],
    correctIndex: 1,
    explanation: "El efecto lost-in-the-middle hace que la información situada al inicio y al final se atienda con mayor fiabilidad.",
  },
  {
    id: "q-safe-retry",
    domain: "context",
    scenario: "Operación externa",
    prompt: "Una tool que procesa pagos responde con un timeout. ¿Qué estrategia es más segura?",
    options: ["Reintentar indefinidamente sin comprobar nada", "Clasificar el error y verificar idempotencia antes de un reintento", "Asumir que el pago no se realizó", "Decir al usuario que se realizó aunque no haya evidencia"],
    correctIndex: 1,
    explanation: "Las operaciones con efectos externos requieren reintentos conscientes de idempotencia y una ruta de escalamiento cuando la evidencia es insuficiente.",
  },
  {
    id: "q-human-loop",
    domain: "context",
    scenario: "Caso ambiguo",
    prompt: "¿Cuándo es apropiado escalar a una persona?",
    options: ["Cuando el riesgo, la ambigüedad o la política requieren revisión", "Nunca: un agente debe resolverlo todo", "Solo al inicio de cada conversación", "Después de inventar una respuesta"],
    correctIndex: 0,
    explanation: "El human-in-the-loop es una capacidad de seguridad: mantiene a la persona en el circuito cuando el caso lo amerita.",
  },
];

const expandedQuestions: Question[] = [
  {
    id: "q-max-tokens",
    domain: "agents",
    scenario: "Agente de soporte al cliente",
    prompt: "Una respuesta termina con stop_reason = max_tokens antes de emitir la recomendación final. ¿Cuál es la reacción correcta?",
    options: ["Mostrar la salida como respuesta final", "Tratarla como truncada y aumentar max_tokens o dividir la tarea", "Interpretar que todas las tools ya se ejecutaron", "Reintentar sin cambiar nada indefinidamente"],
    correctIndex: 1,
    explanation: "max_tokens significa que la generación se interrumpió por el límite. No es una señal de finalización; hay que recuperar la tarea de forma controlada.",
  },
  {
    id: "q-agent-tools-scope",
    domain: "agents",
    scenario: "Sistema de investigación multiagente",
    prompt: "Un agente de análisis de documentos recibe herramientas de búsqueda web, edición de repositorio y pagos, aunque solo debe resumir PDFs. ¿Qué diseño es preferible?",
    options: ["Mantener todas por si el agente las necesita", "Permitir solo las tools de análisis documental necesarias", "Añadir al prompt que ignore las tools irrelevantes", "Ejecutar cada tool antes de iniciar"],
    correctIndex: 1,
    explanation: "La restricción de allowed_tools aplica privilegio mínimo y disminuye decisiones fuera del rol.",
  },
  {
    id: "q-precondition",
    domain: "agents",
    scenario: "Agente de soporte al cliente",
    prompt: "¿Cómo garantizas que process_refund nunca ocurra antes de validar cliente y pedido?",
    options: ["Con una precondición programática que bloquea la llamada", "Con una temperatura más baja", "Con más ejemplos de diálogo", "Con un mensaje de despedida obligatorio"],
    correctIndex: 0,
    explanation: "Una dependencia crítica entre operaciones se impone mediante código o hook, no mediante una preferencia del prompt.",
  },
  {
    id: "q-decomposition",
    domain: "agents",
    scenario: "Revisión de código",
    prompt: "¿Qué estrategia encaja mejor en una revisión amplia de cambios predecibles en muchos archivos?",
    options: ["Un pipeline de análisis por archivo seguido de una pasada de integración", "Una sola pregunta general sin etapas", "Subagentes con las mismas tareas duplicadas", "Una nueva sesión para cada línea modificada"],
    correctIndex: 0,
    explanation: "La revisión multisalto conocida se beneficia de prompt chaining: análisis especializados y síntesis transversal posterior.",
  },
  {
    id: "q-fork-session",
    domain: "agents",
    scenario: "Decisión arquitectónica",
    prompt: "Quieres comparar dos estrategias desde el mismo contexto de investigación sin mezclar sus hallazgos. ¿Qué opción corresponde?",
    options: ["fork_session", "Eliminar el historial", "tool_choice: any", "Un resource MCP"],
    correctIndex: 0,
    explanation: "fork_session crea ramas independientes a partir de un contexto común para explorar alternativas.",
  },
  {
    id: "q-least-privilege-tool",
    domain: "tools",
    scenario: "Análisis documental",
    prompt: "Un agente de documentos usa fetch_url para hacer búsquedas web improvisadas. ¿Cuál es la corrección más robusta?",
    options: ["Cambiar fetch_url por load_document, limitada a formatos de documento", "Pedirle amablemente que no busque", "Aumentar el timeout de fetch_url", "Ocultar los logs de búsqueda"],
    correctIndex: 0,
    explanation: "Una interfaz específica restringe la capacidad al rol y evita el comportamiento fuera de alcance de forma determinista.",
  },
  {
    id: "q-mcp-scope",
    domain: "tools",
    scenario: "Integración de equipo",
    prompt: "Tu equipo entero necesita el servidor MCP de GitHub sin exponer su token. ¿Cómo lo configuras?",
    options: ["En .mcp.json versionado y con ${GITHUB_TOKEN}", "En ~/.claude.json de una sola persona", "Con el token escrito en la descripción de la tool", "En una conversación no versionada"],
    correctIndex: 0,
    explanation: ".mcp.json permite compartir la configuración del proyecto; los secretos se resuelven por variables de entorno.",
  },
  {
    id: "q-grep-glob",
    domain: "tools",
    scenario: "Productividad para desarrolladores",
    prompt: "Necesitas localizar referencias a una función por todo el repositorio antes de leer sus módulos. ¿Qué herramienta integrada eliges primero?",
    options: ["Grep", "Glob", "Write", "Edit"],
    correctIndex: 0,
    explanation: "Grep busca contenido dentro de archivos. Glob se usa para localizar archivos por patrones de nombre o extensión.",
  },
  {
    id: "q-edit-fallback",
    domain: "tools",
    scenario: "Productividad para desarrolladores",
    prompt: "Edit falla porque el texto objetivo aparece varias veces y no hay una coincidencia única. ¿Cuál es el fallback recomendado?",
    options: ["Read + Write sobre el archivo con el cambio inequívoco", "Reintentar Edit sin cambiar nada", "Usar Glob", "Eliminar todas las coincidencias"],
    correctIndex: 0,
    explanation: "Cuando Edit no puede identificar un cambio puntual de manera única, leer y reescribir cuidadosamente es una alternativa más controlable.",
  },
  {
    id: "q-path-rules",
    domain: "code",
    scenario: "Configuración de proyecto",
    prompt: "Una convención debe aplicarse a todos los **/*.test.tsx, estén donde estén. ¿Qué mecanismo encaja mejor?",
    options: ["Una regla .claude/rules con frontmatter paths", "Un CLAUDE.md personal", "Un comentario en un solo test", "Un prompt enviado una vez"],
    correctIndex: 0,
    explanation: "Las reglas con paths cargan de forma condicional para archivos dispersos que comparten un patrón.",
  },
  {
    id: "q-compact",
    domain: "code",
    scenario: "Sesión extensa",
    prompt: "La conversación de Claude Code se volvió extensa y contiene trabajo ya resuelto. ¿Qué comando ayuda a reducir el historial?",
    options: ["/compact", "/memory", "--resume", "tool_choice: auto"],
    correctIndex: 0,
    explanation: "/compact ayuda a condensar contexto; antes hay que preservar de manera estructurada los datos exactos que no pueden perderse.",
  },
  {
    id: "q-headless-json",
    domain: "code",
    scenario: "Integración continua",
    prompt: "Un pipeline necesita que Claude Code devuelva hallazgos que otro paso pueda validar automáticamente. ¿Qué combinación es más apropiada?",
    options: ["Ejecución -p con --output-format json y --json-schema", "Una sesión interactiva con texto libre", "Una captura de pantalla del terminal", "Guardar el resultado solo en memoria"],
    correctIndex: 0,
    explanation: "La ejecución no interactiva y la salida estructurada convierten la revisión en un contrato parseable dentro del pipeline.",
  },
  {
    id: "q-system-message",
    domain: "prompts",
    scenario: "Agente conversacional",
    prompt: "¿Dónde defines el tono, las restricciones y el comportamiento persistente del asistente para una llamada de Messages API?",
    options: ["En el campo system", "Solo en el último mensaje user", "En la respuesta de una tool", "En custom_id de Batch API"],
    correctIndex: 0,
    explanation: "El system prompt establece las reglas de comportamiento y se envía fuera del array de mensajes.",
  },
  {
    id: "q-few-shot-ambiguous",
    domain: "prompts",
    scenario: "Selección de herramientas",
    prompt: "¿Qué pocos ejemplos añaden más valor cuando el modelo confunde dos tools en solicitudes ambiguas?",
    options: ["Ejemplos de casos ambiguos con el motivo de la elección", "Muchos ejemplos idénticos y obvios", "Ejemplos sin resultados", "Solo una lista de nombres de tools"],
    correctIndex: 0,
    explanation: "Los ejemplos comparativos de fronteras ambiguas enseñan el criterio de decisión que falta.",
  },
  {
    id: "q-interview-pattern",
    domain: "prompts",
    scenario: "Arquitectura conversacional",
    prompt: "Un usuario pide “ayúdame con el informe” y cuatro preguntas de aclaración provocan abandono. ¿Cuál es una mejor primera respuesta cuando el riesgo es bajo?",
    options: ["Avanzar con supuestos razonables declarados y permitir corrección", "Exigir un formulario antes de responder", "Elegir supuestos silenciosos", "Finalizar la conversación"],
    correctIndex: 0,
    explanation: "Los supuestos visibles reducen fricción y preservan el control del usuario; la aclaración se reserva para información que cambia materialmente la solución.",
  },
  {
    id: "q-retry-feedback",
    domain: "prompts",
    scenario: "Extracción estructurada",
    prompt: "La validación detecta que el total declarado no coincide con la suma de líneas. ¿Qué retry es más eficaz?",
    options: ["Devolver la discrepancia específica y pedir corrección", "Pedir “hazlo mejor”", "Aceptar el JSON porque es válido", "Cambiar el total de forma silenciosa"],
    correctIndex: 0,
    explanation: "El retry-with-feedback funciona cuando el modelo recibe el error concreto que debe resolver.",
  },
  {
    id: "q-batch-api",
    domain: "prompts",
    scenario: "Procesamiento documental",
    prompt: "¿Cuándo es más adecuado usar Message Batches API?",
    options: ["Para miles de extracciones independientes con latencia diferible", "Para cada turno de un chat en vivo", "Cuando una respuesta depende de la anterior", "Para obligar una tool específica"],
    correctIndex: 0,
    explanation: "Batch API está orientada a volumen asíncrono de solicitudes independientes, no a interacción multi-turn en tiempo real.",
  },
  {
    id: "q-custom-id",
    domain: "prompts",
    scenario: "Message Batches",
    prompt: "¿Para qué sirve custom_id en un lote?",
    options: ["Relacionar cada resultado con su entrada original", "Aumentar max_tokens", "Cifrar el prompt", "Seleccionar un servidor MCP"],
    correctIndex: 0,
    explanation: "custom_id permite reconciliar resultados que pueden llegar en distinto orden o con estado individual distinto.",
  },
  {
    id: "q-case-facts",
    domain: "context",
    scenario: "Soporte multi-turn",
    prompt: "¿Qué información debe salir del historial resumido y vivir en un bloque persistente del caso?",
    options: ["IDs, importes, fechas, preferencias y decisiones confirmadas", "Solo frases de cortesía", "Cualquier texto generado por el modelo", "Únicamente nombres de tools"],
    correctIndex: 0,
    explanation: "Los hechos exactos se degradan en resúmenes narrativos y deben mantenerse como datos estructurados.",
  },
  {
    id: "q-scratchpad",
    domain: "context",
    scenario: "Investigación prolongada",
    prompt: "¿Qué debe contener un scratchpad útil para recuperar una investigación interrumpida?",
    options: ["Hallazgos, fuentes, elementos cubiertos, pendientes y próximos pasos", "Solo la respuesta final", "El prompt de sistema sin cambios", "Una lista de errores sin contexto"],
    correctIndex: 0,
    explanation: "Un estado estructurado permite reanudar sin reconstruir decisiones, cobertura ni evidencia desde cero.",
  },
  {
    id: "q-handoff",
    domain: "context",
    scenario: "Escalamiento de soporte",
    prompt: "¿Qué hace que un handoff a humano sea accionable?",
    options: ["ID, razón, evidencia, pasos ya intentados y acción sugerida", "Solo “necesita ayuda humana”", "El historial completo sin resumen", "Un score global sin explicación"],
    correctIndex: 0,
    explanation: "El handoff debe ser autosuficiente para que la persona continúe el caso con contexto y una recomendación clara.",
  },
  {
    id: "q-partial-coverage",
    domain: "context",
    scenario: "Investigación multiagente",
    prompt: "Dos de cinco fuentes agotaron tiempo, pero las demás son válidas. ¿Cómo debe responder la síntesis?",
    options: ["Entregar resultados y marcar de forma explícita las áreas con cobertura parcial", "Ocultar las fuentes fallidas", "Descartar todo el trabajo", "Inventar una fuente equivalente"],
    correctIndex: 0,
    explanation: "Las anotaciones de cobertura mantienen el valor del trabajo y hacen visible la incertidumbre para la siguiente decisión.",
  },
  {
    id: "q-provenance-conflict",
    domain: "context",
    scenario: "Investigación multiagente",
    prompt: "Dos fuentes creíbles dan 12% y 40% para la misma métrica. ¿Qué preserva mejor la confiabilidad?",
    options: ["Conservar ambos valores con fuente y fecha, y escalar la reconciliación", "Elegir la cifra más alta", "Promediar sin explicación", "Eliminar toda la sección"],
    correctIndex: 0,
    explanation: "La provenance mantiene la evidencia y el conflicto visible; el coordinador o una regla posterior puede decidir cómo reconciliarlo.",
  },
];

export const questions = [...coreQuestions, ...expandedQuestions];

export const matchPairs = [
  { left: "tool_choice: any", right: "Exige al menos una llamada a herramienta" },
  { left: "PreToolUse", right: "Bloquea o redirige antes de ejecutar" },
  { left: "Resource MCP", right: "Aporta contexto sin ejecutar una acción" },
  { left: "CLAUDE.md de proyecto", right: "Comparte reglas versionadas con el equipo" },
  { left: "Campo nullable", right: "Representa información ausente sin inventarla" },
];

export const agentLoopSteps = [
  "Enviar solicitud al modelo con las tools disponibles",
  "Recibir la respuesta y revisar stop_reason",
  "Ejecutar la tool cuando stop_reason es tool_use",
  "Añadir el resultado de la tool al historial",
  "Repetir la solicitud hasta recibir end_turn",
];

export const sourceRepository = "https://github.com/paullarionov/claude-certified-architect";
